#DATASOURCE H2
#spring.datasource.url=jdbc:h2:mem:epictask
#spring.datasource.username=sa
#spring.datasource.password=

#DATASOURCE MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/epictask
spring.datasource.username=root
spring.datasource.password=rootmysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
